### ISSUE TITLE
Crash when trying to scan with large netmasks

### ISSUE THREAD

**Issue by pangloss** [jas-/node-libnmap#12]
For instance, if I specify a range of `10.0.0.0/21`, I get the following exception:

```
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:788:15)
    at Object.exports.exec (child_process.js:649:18)
    at /Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/lib/node-libnmap.js:89:22
    at /Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/node_modules/async/lib/async.js:227:13
    at /Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/node_modules/async/lib/async.js:32:24)
    at async.each (/Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/node_modules/async/lib/async.js:110:9)
    at _asyncMap (/Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/node_modules/async/lib/async.js:226:9)
    at Object.map (/Users/dw/dev/lightmesh.cli/node_modules/node-libnmap/node_modules/async/lib/async.js:204:23)
Error: spawn /bin/sh EAGAIN
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
```

I got the same error testing with /21, /20, /19, /18, and did not test further.

**Comment by jas-** [comment]
@pangloss This is covered in the `ulimit` section of the `readme` document. Please read the manual.

**Comment by pangloss** [comment]
Rather than requiring clients to reconfigure their computer, which makes this library fairly useless, perhaps it would be better to limit the number of concurrent, if you know how.

**Comment by jas-** [comment]
@pangloss You're right, System limitations to protect file handle and socket handle limits are there for everyone to circumvent with clever programming. If you own a class A or B network perhaps you can find a nice paid for product as I am sure you have the budget for it. ;)
