### ISSUE TITLE
Error: Callback was already called (again).

### ISSUE THREAD

**Issue by Kikobeats** [jas-/node-libnmap#24]
```bash
npm test

> node-libnmap@0.2.10 test /Users/josefranciscoverdugambin/Downloads/node-libnmap
> mocha -R spec



  nmap
    discovery method
      1) validate report
      ✓ validate report (57ms)
    nmap
    nmap
      error handling
        scan method
          ✓ default (580ms)
          ✓ xml report
          ✓ invalid host range (host)
          ✓ invalid host range (range)
          ✓ invalid host range (CIDR)
          ✓ invalid port range

  7 passing (870ms)
  1 failing

  1) nmap discovery method validate report:
     Uncaught Error: Callback was already called.
      at node_modules/async/lib/async.js:43:36
      at node_modules/async/lib/async.js:694:17
      at node_modules/async/lib/async.js:173:37
      at Object.reporting.reports (lib/node-libnmap.js:138:16)
      at Socket.errbytesend (lib/node-libnmap.js:227:32)
      at _stream_readable.js:908:16



npm ERR! Test failed.  See above for more details.
```

**Comment by tomtom87** [comment]
+1

**Comment by jas-** [comment]
@tomtom87 @Kikobeats, I am unable to re-create this error. I am going to need some more information.

Do any of the `examples/*.js` files work? What version of nodejs are you running? Anything prior to `v0.11.7` doesn't contain the necessary `mac` [attribute population](https://nodejs.org/api/os.html#os_os_networkinterfaces) necessary for the `discover` method.

**Comment by Kikobeats** [comment]
I checked now and works fine with v0.12+!

**Comment by jas-** [comment]
Good to hear. Just so you're aware with the release of `v0.2.15` the name has changed to `libnmap` so to keep your project's module dependency up to date you should use `npm --save install libnmap`. Thanks for reporting this.
