### ISSUE TITLE
Error: Callback was already called (again again again).

### ISSUE THREAD

**Issue by raphaelsoul** [jas-/node-libnmap#51]
```
# raphaelsoul at Koishi-no-MBP.local in ~/hacker/node_modules/libnmap [18:32:38]
→ npm test

> libnmap@0.4.9 test /Users/raphaelsoul/hacker/node_modules/libnmap
> mocha -R spec



  nmap
    discovery method
      ✓ validate report (189ms)
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      ✓ invalid flag options (366ms)
      ✓ unspecified range

  scan method
    reporting
      ✓ json (10046ms)
      ✓ xml (9892ms)


  10 passing (21s)
  1 failing

  1) nmap
       discovery method
         validate report:
     Error: done() called multiple times
      at test/discover.js:28:17
      at discover (lib/libnmap.js:645:16)
      at node_modules/async/dist/async.js:3874:9
      at node_modules/async/dist/async.js:473:16
      at iterateeCallback (node_modules/async/dist/async.js:980:24)
      at node_modules/async/dist/async.js:958:16
      at node_modules/async/dist/async.js:3871:13
      at parseXML (lib/libnmap.js:149:18)
      at Parser.<anonymous> (node_modules/xml2js/lib/parser.js:303:18)
      at SAXParser.onclosetag (node_modules/xml2js/lib/parser.js:261:26)
      at emit (node_modules/sax/lib/sax.js:624:35)
      at emitNode (node_modules/sax/lib/sax.js:629:5)
      at closeTag (node_modules/sax/lib/sax.js:889:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1436:13)
      at Parser.exports.Parser.Parser.parseString (node_modules/xml2js/lib/parser.js:322:31)
      at Parser.parseString (node_modules/xml2js/lib/parser.js:5:59)
      at Object.reports (lib/libnmap.js:145:19)
      at Socket.bytesend (lib/libnmap.js:316:32)
      at endReadableNT (_stream_readable.js:1059:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)



npm ERR! Test failed.  See above for more details.
```

I am using `libnmap@0.4.9`.  
sorry for again again again 🤣

**Comment by jas-** [comment]
@raphaelsoul since this issue is happening with the `discover` method, can you enable debugging with `{verbose:true}` in the `examples/discover.js` example file and post the output? Thanks.

**Comment by raphaelsoul** [comment]
if only set `verbose`, throw error as bellow:
```
node examples/discover.js
/Users/raphaelsoul/node-libnmap/examples/discover.js:12
  if (err) throw new Error(err);
           ^

Error: Error: Range must be an array of host(s). Examples: 192.168.2.10 (single), 10.0.2.0/24 (CIDR), 10.0.10.5-20 (range)
    at /Users/raphaelsoul/node-libnmap/examples/discover.js:12:18
    at config (/Users/raphaelsoul/node-libnmap/lib/libnmap.js:653:16)
    at validation.init (/Users/raphaelsoul/node-libnmap/lib/libnmap.js:101:18)
    at Object.init (/Users/raphaelsoul/node-libnmap/lib/libnmap.js:587:36)
    at Object.init (/Users/raphaelsoul/node-libnmap/lib/libnmap.js:99:18)
    at nmap.discover (/Users/raphaelsoul/node-libnmap/lib/libnmap.js:651:12)
    at Object.<anonymous> (/Users/raphaelsoul/node-libnmap/examples/discover.js:11:6)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```
@jas- seems caused by default options

when i set `{ verbose: true,  range: ['192.168.0.0-255']}`, function `discover` runs without error.

**Comment by jas-** [comment]
Are you using `OSX`? Can you provide details on your network stack and node.js version as well?

**Comment by raphaelsoul** [comment]
```
uname -a
Darwin Koishi-no-MBP.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

# raphaelsoul at Koishi-no-MBP.local in ~/node-libnmap on git:master ✖︎ [12:01:25]
→ node -v
v8.5.0
```

```
→ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC1: flags=0<> mtu 0
XHC20: flags=0<> mtu 0
XHC0: flags=0<> mtu 0
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x7
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 78:4f:43:8b:39:aa
	inet6 fe80::14be:2442:8b00:8400%en0 prefixlen 64 secured scopeid 0x8
	inet 192.168.0.100 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```
Yes, osx. Detail above

**Comment by jas-** [comment]
Awesome. Thank you for that. I believe the bug is with two interfaces using `IPv6`.

What is the output of `console.log(require('os).networkInterfaces()`

**Comment by raphaelsoul** [comment]
macOS:
```
> require('os').networkInterfaces()
{ lo0:
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true,
       cidr: '127.0.0.1/8' },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true,
       cidr: '::1/128' },
     { address: 'fe80::1',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 1,
       internal: true,
       cidr: 'fe80::1/64' } ],
  en5:
   [ { address: 'fe80::xxxx:xxxx:xxxx:1122',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'xx:xx:xx:xx:xx:xx',
       scopeid: 7,
       internal: false,
       cidr: 'fe80::xxxx:xxxx:xxxx:1122/64' } ],
  en0:
   [ { address: 'fe80::xxxx:xxxx:xxxx:8400',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '78:xx:xx:xx:xx:aa',
       scopeid: 8,
       internal: false,
       cidr: 'fe80::xxxx:xxxx:xxxx:8400/64' },
     { address: '192.168.0.100',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: '78:xx:xx:xx:xx:aa',
       internal: false,
       cidr: '192.168.0.100/24' } ],
  awdl0:
   [ { address: 'fe80::a8c9:ddff:fe11:18be',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'aa:c9:dd:11:18:be',
       scopeid: 10,
       internal: false,
       cidr: 'fe80::a8c9:ddff:fe11:18be/64' } ],
  utun0:
   [ { address: 'fe80::xxxx:xxxx:xxxx:fdd2',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 16,
       internal: false,
       cidr: 'fe80::xxxx:xxxx:xxxx:fdd2/64' } ] }
```

Linode:
```
> require('os').networkInterfaces()
{ lo:
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true,
       cidr: '127.0.0.1/8' },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true,
       cidr: '::1/128' } ],
  eth0:
   [ { address: '139.xxx.xxx.136',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'f2:xx:xx:xx:xx:23',
       internal: false,
       cidr: '139.xxx.xxx.136/24' },
     { address: '2400:xxxx::xxxx:xxxx:xxxx:bc23',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'f2:xx:xx:xx:xx:23',
       scopeid: 0,
       internal: false,
       cidr: '2400:xxxx::xxxx:xxxx:xxxx:bc23/64' },
     { address: 'fe80::xxxx:xxxx:xxxx:bc23',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'f2:xx:xx:xx:xx:23',
       scopeid: 3,
       internal: false,
       cidr: 'fe80::xxxx:xxxx:xxxx:bc23/64' } ] }
```

**Comment by jas-** [comment]
Hmm, I think I have a typo... can you remove the ` ` on [line #253](https://github.com/jas-/node-libnmap/blob/v0.4.9/lib/libnmap.js#L253) and try?

**Comment by jas-** [comment]
Can you try the latest branch `v0.4.11`? I think your multiple addresses per interface was not being handled, this branch should now support the `RFC 7934` & `RFC 4218 & 4219`

**Comment by raphaelsoul** [comment]
```
# raphaelsoul at Koishi-no-MBP.local in ~/sdk/node-libnmap on git:v0.4.11 ✖︎ [15:19:44]
→ npm test

> libnmap@0.4.11 test /Users/raphaelsoul/sdk/node-libnmap
> mocha -R spec



  nmap
    discovery method
      ✓ validate report
      1) validate report

  nmap
    error handling
      ✓ missing nmap binary
      ✓ invalid host range (host)
      ✓ invalid host range (range)
      ✓ invalid host range (CIDR)
      ✓ invalid port range
      ✓ invalid flag options (341ms)
      ✓ unspecified range

  scan method
    reporting
      ✓ json (10749ms)
      ✓ xml (10464ms)


  10 passing (22s)
  1 failing

  1) nmap
       discovery method
         validate report:
     Error: done() called multiple times
      at /Users/raphaelsoul/sdk/node-libnmap/test/discover.js:30:17
      at config (lib/libnmap.js:72:16)
      at validation.init (lib/classes/tools.js:215:16)
      at validation.init (lib/classes/validation.js:135:34)
      at tools.init (lib/classes/tools.js:213:16)
      at nmap.discover (lib/libnmap.js:70:11)
      at Context.<anonymous> (test/discover.js:23:12)



npm ERR! Test failed.  See above for more details.
```

**Comment by jas-** [comment]
Could you run the `node examples/discovery.js` example with `{debug: true}` enabled? The first couple of lines should provide the CIDR notation per interface found for discovery. That is what I would like to see since I do not have a good test environment ATM to replicate your configuration.

**Comment by raphaelsoul** [comment]
if set `{ debug:true }` only:
```
# raphaelsoul at Koishi-no-MBP.local in ~/sdk/node-libnmap on git:v0.4.11 ✖︎ [15:31:59]
→ node examples/discover.js
Caught exception: Error: Error: Range must be an array of host(s). Examples: 192.168.2.10 (single), 10.0.2.0/24 (CIDR), 10.0.10.5-20 (range)
```

yet i tried 
```
{
    debug: true.
    range: ['192.168.0.0/24']
}
``
got report successfully

**Comment by jas-** [comment]
You may need to re-clone `v0.4.11` to commit [722fea8](https://github.com/jas-/node-libnmap/commit/722fea8cc93ad30408d1ee2a49945d73dd5978c6)

**Comment by jas-** [comment]
@raphaelsoul I am going to close this as the latest is now `v0.4.16`. If this is still an issue please provide additional details using the `verbose: true` option with the provided [discover.js](https://github.com/jas-/node-libnmap/blob/master/examples/discover.js). Thanks.
