### ISSUE TITLE
Application crashes after second execution

### ISSUE THREAD

**Issue by vladei** [jas-/node-libnmap#7]
Hi there :),

Thank you for writing this library. I've integrated node-libnmap to one of my applications and I run it using a cron job. When I initiate the server the job is running perfectly fine for the first time. When cron runs the job for second time the server crashes:

```
/node/whoishome/node_modules/node-libnmap/lib/node-libnmap.js:215
          throw new Error('Range must be an array of host(s), examples:' +
                ^
Error: Range must be an array of host(s), examples:[192.168.2.10 (single), 10.0.2.0/24 (CIDR), 10.0.10.5-20] (range)
    at Object.setup.verify (/node/whoishome/node_modules/node-libnmap/lib/node-libnmap.js:215:17)
    at Object.methods.scan (/node/whoishome/node_modules/node-libnmap/lib/node-libnmap.js:78:13)
    at Object.nmap (/node/whoishome/node_modules/node-libnmap/lib/node-libnmap.js:609:28)
    at CronJob.<anonymous> (/node/whoishome/jobs/scan.network.js:14:26)
    at callbackWrapper [as _onTimeout] (/node/whoishome/node_modules/cron/lib/cron.js:427:24)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

```
The job I've written is this:

```

var CronJob = require('cron').CronJob;

//Set up for scan
var scanOptions = {
  nmap: '/usr/local/bin/nmap',
  range: ['localhost', '192.168.1.0/25'],
  ports: '9000,9001'
}


// EVERY MINUTE
var job = new CronJob('* * * * *', function(){
	console.log('Scan started at '+ new Date());
	require('node-libnmap').nmap('scan', scanOptions, function(err, report){
	  if (err) console.log(err);
	  	console.log('Scan completed at '+ new Date());
	    console.log(report);
	})
}, null, true, "America/Los_Angeles");

````

**Comment by jas-** [comment]
The `scanOptions` object looses scope during the second iteration of your scheduled task. Try this use case.

```javascript
var CronJob = require('cron').CronJob;

// EVERY MINUTE
var job = new CronJob('* * * * *', function(){

    //Set up for scan
    var scanOptions = {
      nmap: '/usr/local/bin/nmap',
      range: ['localhost', '192.168.1.0/25'],
      ports: '9000,9001'
    }

    console.log('Scan started at '+ new Date());
    require('node-libnmap').nmap('scan', scanOptions, function(err, report){
      if (err) console.log(err);
        console.log('Scan completed at '+ new Date());
        console.log(report);
    })
}, null, true, "America/Los_Angeles");
```
